project:
  type: website

website:
  title: "Anthony Mora"
  page-navigation: true
  navbar:
    background: '#5b4bcd'
    foreground: '#f2e277'
    left:
      - about.qmd
      - text: Blog
        url: 'blog.html'
  
  page-footer: 
    center: 
      - text: 'About'
        

  

format:
  html:
    toc: true



